### ISSUE TITLE
Not working issue

### ISSUE THREAD

**Issue by Andrejki** [megadose/Quidam#7]
Hello.
The code is simply not working. It is the great tool, but I can t get it to work.
I ve tried to see coding and lines and to start with python3 even core.py, but something is wrong.
It is working for non of the mentioned websites. 
I ve tried using both Twitter names, Instagram names, and Github names.

You select all
Email extract with instagram of andrejki: NULL
Not informations found
Traceback (most recent call last):
  File "quidam.py", line 77, in <module>
    info = github(args.username)
  File "/home/andrejki/Quidam/quidam/core.py", line 74, in github
    if r.get('message', '') == 'Not Found':
AttributeError: 'list' object has no attribute 'get'

Best regards

Edit: I did merge the correct typo - same errors.

**Comment by Andrejki** [comment]
Hi. Any updates? :)

**Comment by Andrejki** [comment]
Hi. Not updates on the project, but updates regarding installation instructions? 
Best regards
