### ISSUE TITLE
Evolut dependency is broken

### ISSUE THREAD

**Issue by HelifeWasTaken** [megadose/Quidam#8]
`python3 quidam.py -m twitter -u user`
```
You select twitter
Traceback (most recent call last):
  File "/tmp/Quidam/quidam.py", line 41, in <module>
    info = twitter(args.username)
  File "/tmp/Quidam/quidam/core.py", line 58, in twitter
    info = evolut(username)
  File "/usr/local/lib/python3.10/dist-packages/evolut-1.4-py3.10.egg/evolut/core.py", line 50, in evolut
    return({"phone":phone,"email":email})
UnboundLocalError: local variable 'phone' referenced before assignment
```

**Comment by HelifeWasTaken** [comment]
Simple fix at line 50, 51:
```
        phone = int(info[1].text)
        email = str(info[0].text)
```

**Comment by HelifeWasTaken** [comment]
#10 #9
